// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNf-MIItdk1Z-46OVkcbjlFcgh8dHQO1w',
    appId: '1:734059529982:web:59d91a4f959498f3a247af',
    messagingSenderId: '734059529982',
    projectId: 'talnio-50dd4',
    authDomain: 'talnio-50dd4.firebaseapp.com',
    storageBucket: 'talnio-50dd4.firebasestorage.app',
    measurementId: 'G-7M3RQ8F5Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9LCpLqRzspyYPkMaDTJlpKC0lyY482IY',
    appId: '1:734059529982:android:f013dfe2d9beeeaba247af',
    messagingSenderId: '734059529982',
    projectId: 'talnio-50dd4',
    storageBucket: 'talnio-50dd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHiVmtnB2cV24uP2CkL2kGIToxPd0Emo8',
    appId: '1:734059529982:ios:a1d6975909b0c1dfa247af',
    messagingSenderId: '734059529982',
    projectId: 'talnio-50dd4',
    storageBucket: 'talnio-50dd4.firebasestorage.app',
    iosBundleId: 'com.talnio.talnio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHiVmtnB2cV24uP2CkL2kGIToxPd0Emo8',
    appId: '1:734059529982:ios:a1d6975909b0c1dfa247af',
    messagingSenderId: '734059529982',
    projectId: 'talnio-50dd4',
    storageBucket: 'talnio-50dd4.firebasestorage.app',
    iosBundleId: 'com.talnio.talnio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNf-MIItdk1Z-46OVkcbjlFcgh8dHQO1w',
    appId: '1:734059529982:web:625f8c574d151d89a247af',
    messagingSenderId: '734059529982',
    projectId: 'talnio-50dd4',
    authDomain: 'talnio-50dd4.firebaseapp.com',
    storageBucket: 'talnio-50dd4.firebasestorage.app',
    measurementId: 'G-BP3MPR0X77',
  );
}
